amcl:
  ros__parameters:
    global_frame_id: map
    base_frame_id: base_link
    odom_frame_id: odom
    map_topic: map
    scan_topic: /scan
    tf_broadcast: true
    transform_tolerance: 1.0
    introspection_mode: disabled

    first_map_only: true
    set_initial_pose: true
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
    always_reset_initial_pose: true
    save_pose_rate: -1.0

    # Sensor Models
    laser_model_type: likelihood_field # beam | likelihood_field | likelihood_field_prob
    max_beams: 60
    laser_min_range: -1.0
    laser_max_range: -1.0
    laser_likelihood_max_dist: 2.0

    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    sigma_hit: 0.2
    lambda_short: 0.1

    do_beamskip: false # used only on the "likelihood_field_prob"
    beam_skip_distance: 0.5
    beam_skip_threshold: 0.3
    beam_skip_error_threshold: 0.9

    # Motion Models
    robot_model_type: nav2_amcl::DifferentialMotionModel # nav2_amcl::DifferentialMotionModel | nav2_amcl::OmniMotionModel
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2

    # Core parameters
    min_particles: 500
    max_particles: 2000
    pf_err: 0.05
    pf_z: 2.33
    update_min_d: 0.1
    update_min_a: 0.1
    resample_interval: 1

    # More informations: https://docs.nav2.org/configuration/packages/configuring-amcl.html#parameters
